SRC_DIR = ./src
BUILD_DIR = ./build
TARGET = $(BUILD_DIR)/elf-tool

CC = gcc
CFLAGS = -Wall

# find all source file
SRCS = $(shell find $(SRC_DIR) -name '*.c')
# decide all the object files
OBJS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.o, $(SRCS))
# find all the header files
DEPS = $(patsubst $(SRC_DIR)/%.c, $(BUILD_DIR)/%.d, $(SRCS))

all: $(TARGET)

# all deps file decided by .c files
# use cc -MM options to generate the deps
$(BUILD_DIR)/%.d: $(SRC_DIR)/%.c
	@mkdir -p $(dir $@); \
	rm -rf $@; \
	$(CC) -MM $< >$@.tmp; \
	sed 's,\($*\)\.o[ :]*,$(BUILD_DIR)/\1.o $@ : ,g' < $@.tmp > $@; \
	rm -f $@.tmp
	rm -f $@.d
	rm -rf $@

# all the object is generated by the .c files
$(BUILD_DIR)/%.o: $(SRC_DIR)/%.c
	$(CC) $(CFLAGS) -c -o $@ $<

# link all the object files
$(TARGET): $(OBJS)
	$(CC) $(OBJS) -lelf -o $(TARGET)

clean:
	rm -rf $(BUILD_DIR)/*

# include all the deps
-include $(DEPS) 
